# Compare mse/hellinger outputs: OLD inline code vs NEW catfda library
#
# OLD files: outputs/clustersims/A_1_multinomial_testvalues/
#   Pattern : ClusterSim_{n}_{t}_A_1_multinomial_TRUE.RData
#   Contains: est_values  (generated by xj_clustering.R)
#
# NEW files: outputs/clustersims/A_1_multinomial_Table1Data/
#   Pattern : ClusterSim_{n}_{t}_A_1_multinomial_TRUE_neworder.RData
#   Contains: est_values  (generated by xj_clustering_newlib.R / catfda library)
#
# Both est_values have: $mse [2x3], $hellinger [3x3]

# ---- Parameters ----
num_indvs  <- 100         # change to 100, 500, or 1000
scenario   <- "A"
num_replicas <- 2
est_choice <- "multinomial"
old_identifier <- "to_compare_old_code"
new_identifier <- "to_compare_new_code"
t_lengths  <- c(300, 750, 2000)
# --------------------

old_folder <- file.path("outputs", "clustersims",
                        paste(scenario, num_replicas, est_choice, old_identifier, sep = "_"))
new_folder <- file.path("outputs", "clustersims",
                        paste(scenario, num_replicas, est_choice, new_identifier, sep = "_"))

cat("Old folder:", old_folder, "\n")
cat("New folder:", new_folder, "\n\n")

# Helper: load est_values from one file into a private environment
load_est_values <- function(folder, n, t, suffix = "") {
  fname <- paste0("ClusterSim_", n, "_", t, "_", scenario, "_", num_replicas,
                  "_", est_choice, "_TRUE", suffix, ".RData")
  fpath <- file.path(folder, fname)
  if (!file.exists(fpath)) stop(paste("File not found:", fpath))
  e <- new.env()
  load(fpath, envir = e)
  stopifnot(!is.null(e$est_values$mse), !is.null(e$est_values$hellinger))
  e$est_values
}

old_results <- lapply(t_lengths, function(t) load_est_values(old_folder, num_indvs, t, suffix = ""))
new_results <- lapply(t_lengths, function(t) load_est_values(new_folder, num_indvs, t, suffix = "_neworder"))
names(old_results) <- names(new_results) <- paste0("t", t_lengths)

# Build a 9x5 mse_table (same structure as used in RunExperiment)
mse_row <- function(r, cluster_col) {
  c(r$mse[1, cluster_col],
    r$mse[2, cluster_col],
    r$hellinger[1, cluster_col],
    r$hellinger[2, cluster_col],
    r$hellinger[3, cluster_col])
}

build_mse_table <- function(results, n) {
  tbl <- do.call(rbind, lapply(1:3, function(cluster_col) {
    do.call(rbind, lapply(results, function(r) mse_row(r, cluster_col)))
  }))
  rownames(tbl) <- as.vector(outer(paste0("s", 1:3, "n", n), paste0("t", t_lengths), paste0))
  colnames(tbl) <- c("z1", "z2", "p1", "p2", "p3")
  tbl
}

old_table <- build_mse_table(old_results, num_indvs)
new_table <- build_mse_table(new_results, num_indvs)

# Print both tables transposed (p1/p2/p3/z1/z2 as rows) for easy reading
fmt <- function(tbl) round(t(tbl)[c("p1", "p2", "p3", "z1", "z2"), ], 4)

cat("===== OLD (inline code) =====\n")
print(fmt(old_table))

cat("\n===== NEW (catfda library) =====\n")
print(fmt(new_table))

cat("\n===== DIFFERENCE (new - old) =====\n")
diff_table <- new_table - old_table
print(fmt(diff_table))

cat("\n===== MAX ABSOLUTE DIFFERENCE per metric =====\n")
max_diff <- apply(abs(diff_table), 2, max)
print(round(max_diff, 6))
